---
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /var/www
    state: directory
    mode: '0775'

- name: install git
  shell: |
    yum -y install git pip nginx



